apiVersion: v1
kind: Template
labels:
  template: scrumola-backend
metadata:
  name: scrumola-backend
  annotations:
    description: scrumola-backend
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: scrumola-backend
    name: scrumola-backend
  spec:
    selector:
      service: scrumola-backend
    template:
      metadata:
        labels:
          service: scrumola-backend
      spec:
        containers:
        - env:
          - name: GUNICORN_CMD_ARGS
            value: "${GUNICORN_CMD_ARGS}"
          image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
          name: scrumola-backend
          ports:
          - containerPort: 5000
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "512Mi"
              cpu: "500m"
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
    replicas: ${{REPLICAS}}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: scrumola-backend
    name: scrumola-backend
  spec:
    ports:
    - name: "32000"
      port: 32000
      protocol: TCP
      targetPort: 5000
    selector:
      service: scrumola-backend
- apiVersion: v1
  kind: Route
  metadata:
    name: scrumola-backend
  spec:
    host: ${BAYESIAN_API_HOSTNAME}
    to:
      kind: Service
      name: scrumola-backend

parameters:
- description: Docker registry where the image is
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "rratnawa"

- description: Docker image to use
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "scrumola-backend"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"  # image-tag

- description: Number of deployment replicas
  displayName: Number of deployment replicas
  required: true
  name: REPLICAS
  value: "1"

- description: Settings for Gunicorn
  displayName: Settings for Gunicorn
  required: true
  name: GUNICORN_CMD_ARGS
  value: "-b :5000 --workers=4"
